// Generated by CoffeeScript 1.4.0
/*

  SongLocator.

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var BaseResolver, EventEmitter, XMLHttpRequest, exports, extend, idCounter, uniqueId, urlencode, xhrGET,
  __slice = [].slice;

XMLHttpRequest = XMLHttpRequest || require('xmlhttprequest').XMLHttpRequest;

urlencode = function(params) {
  var k, v;
  params = (function() {
    var _results;
    _results = [];
    for (k in params) {
      v = params[k];
      _results.push("" + k + "=" + (encodeURIComponent(v.toString())));
    }
    return _results;
  })();
  return params.join('&');
};

xhrGET = function(options) {
  var callback, params, rawResponse, request, url;
  url = options.url, params = options.params, callback = options.callback, rawResponse = options.rawResponse;
  url = "" + url + "?" + (urlencode(params));
  request = new XMLHttpRequest();
  request.open('GET', url, true);
  request.addEventListener('readystatechange', function() {
    var data;
    if (request.readyState !== 4) {
      return;
    }
    if (request.status === 200) {
      data = rawResponse ? request.responseText : JSON.parse(request.responseText);
      return callback(void 0, data);
    } else {
      return callback(request, void 0);
    }
  });
  return request.send();
};

extend = function() {
  var k, o, obj, objs, v, _i, _len;
  obj = arguments[0], objs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  for (_i = 0, _len = objs.length; _i < _len; _i++) {
    o = objs[_i];
    for (k in o) {
      v = o[k];
      obj[k] = v;
    }
  }
  return obj;
};

idCounter = 0;

uniqueId = function(prefix) {
  var id;
  id = ++idCounter + '';
  if (prefix) {
    return prefix + id;
  } else {
    return id;
  }
};

EventEmitter = {
  on: function(name, callback) {
    var handlers, list;
    if (!this.hasOwnProperty("_handlers")) {
      this._handlers = {};
    }
    handlers = this._handlers;
    if (!handlers.hasOwnProperty(name)) {
      handlers[name] = [];
    }
    list = handlers[name];
    return list.push(callback);
  },
  once: function(name, callback) {
    var remove,
      _this = this;
    remove = function() {
      _this.off(name, callback);
      return _this.off(name, remove);
    };
    this.on(name, callback);
    return this.on(name, remove);
  },
  emit: function() {
    var args, handlers, l, list, name, _i, _len, _results;
    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (!this.hasOwnProperty("_handlers")) {
      return;
    }
    handlers = this._handlers;
    if (!handlers.hasOwnProperty(name)) {
      return;
    }
    list = handlers[name];
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      l = list[_i];
      if (!l) {
        continue;
      }
      _results.push(l.apply(this, args));
    }
    return _results;
  },
  off: function(name, callback) {
    var handlers, index, list, _results;
    if (!this.hasOwnProperty("_handlers")) {
      return;
    }
    handlers = this._handlers;
    if (!handlers.hasOwnProperty(name)) {
      return;
    }
    list = handlers[name];
    index = list.indexOf(callback);
    if (index < 0) {
      return;
    }
    list[index] = false;
    if (index === list.length - 1) {
      _results = [];
      while (index >= 0 && !list[index]) {
        list.length--;
        _results.push(index--);
      }
      return _results;
    }
  }
};

EventEmitter.addListener = EventEmitter.on;

EventEmitter.addEventListener = EventEmitter.on;

EventEmitter.removeListener = EventEmitter.off;

EventEmitter.removeEventListener = EventEmitter.off;

EventEmitter.trigger = EventEmitter.emit;

BaseResolver = (function() {

  extend(BaseResolver.prototype, EventEmitter);

  BaseResolver.prototype.name = void 0;

  BaseResolver.prototype.options = {
    includeRemixes: true,
    includeCovers: true,
    includeLive: true
  };

  function BaseResolver(options) {
    this.options = extend({}, this.options, options);
  }

  BaseResolver.prototype.request = function(opts) {
    return xhrGET(opts);
  };

  BaseResolver.prototype.search = function(qid, query) {};

  BaseResolver.prototype.resolve = function(qid, track, artist, album) {};

  BaseResolver.prototype.results = function(qid, results) {
    if (((results != null ? results.length : void 0) != null) && results.length > 0) {
      return this.emit('results', {
        qid: qid,
        results: results || []
      });
    }
  };

  BaseResolver.prototype.searchDebug = function(query) {
    var qid;
    qid = uniqueId('query');
    this.once('results', function(results) {
      return console.log(results.results);
    });
    return this.search(qid, query);
  };

  BaseResolver.prototype.resolveDebug = function(track, artist, album) {
    var qid;
    qid = uniqueId('resolve');
    this.once('results', function(results) {
      return console.log(results.results);
    });
    return this.resolve(qid, track, artist, album);
  };

  return BaseResolver;

})();

if (typeof window !== "undefined" && window !== null) {
  window.SongLocator = window.SongLocator || {};
  extend(window.SongLocator, exports);
}

exports = {
  extend: extend,
  urlencode: urlencode,
  xhrGET: xhrGET,
  uniqueId: uniqueId,
  BaseResolver: BaseResolver
};
