// Generated by CoffeeScript 1.4.0
/*

  SongLocator resolver for rdio.

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var BaseResolver, Resolver, extend, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ref = require('./songlocator-base'), BaseResolver = _ref.BaseResolver, extend = _ref.extend;

Resolver = (function(_super) {

  __extends(Resolver, _super);

  function Resolver() {
    return Resolver.__super__.constructor.apply(this, arguments);
  }

  Resolver.prototype.name = 'rdio';

  Resolver.prototype.score = 0.9;

  Resolver.prototype.search = function(qid, query) {
    var _this = this;
    return this.request({
      method: 'POST',
      url: 'http://api.rdio.com/1/',
      params: {
        method: 'search',
        query: query,
        types: 'Track'
      },
      callback: function(error, response) {
        if (error != null) {
          return;
        }
        if (!(response.data.length > 0)) {
          return;
        }
        return console.log(response);
      }
    });
  };

  return Resolver;

})(BaseResolver);

extend(exports, {
  Resolver: Resolver
});

if (typeof window !== "undefined" && window !== null) {
  if (!(window.SongLocator != null)) {
    throw new Error('no songlocator-base module was loaded');
  }
  window.SongLocator.Rdio = {};
  extend(window.SongLocator.Rdio, exports);
}
